In [5]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import sys
import seaborn as sns; sns.set()


    

In [4]:
array = np.arange(1000)
a = 
print(array.size*array.itemsize)

array2 = np.arange(1000)
result = [(x + y) for x, y in zip(array, array2)]


TypeError: 'numpy.ndarray' object is not callable

In [12]:
a = np.array(np.random.randn(4, 4, 2))
print(a.ndim)
print(a)

3
[[[ 0.88090636 -0.03861493]
  [ 0.59454374  0.87057752]
  [ 0.3913207   0.17822361]
  [-2.36394285 -0.66311528]]

 [[ 1.26933878  0.24108847]
  [ 0.34337032 -0.16724024]
  [ 0.18806855  0.40522419]
  [-0.38440686 -1.76725822]]

 [[-1.3624359   0.00885936]
  [-0.02806737  0.53971363]
  [-0.57162587 -0.30176184]
  [ 0.66447928  0.52536199]]

 [[ 0.19193372 -0.47994978]
  [-0.65010788  0.88364199]
  [ 0.58964144  0.92388108]
  [-0.48643678  0.7025045 ]]]


In [23]:
b = np.array([[1, 1], [3, 3]], dtype= np.int32)
a.dtype
b.dtype

a.size #total element
a.shape #dimensions

np.zeros((4, 4))
np.linspace(1, 10, 3)

#a.reshape(8, 4)
a.ravel()

array([ 0.88090636, -0.03861493,  0.59454374,  0.87057752,  0.3913207 ,
        0.17822361, -2.36394285, -0.66311528,  1.26933878,  0.24108847,
        0.34337032, -0.16724024,  0.18806855,  0.40522419, -0.38440686,
       -1.76725822, -1.3624359 ,  0.00885936, -0.02806737,  0.53971363,
       -0.57162587, -0.30176184,  0.66447928,  0.52536199,  0.19193372,
       -0.47994978, -0.65010788,  0.88364199,  0.58964144,  0.92388108,
       -0.48643678,  0.7025045 ])

In [31]:
#Mathematical Functions

#a.max()
#a.min()
#a.sum()

# There is this idea of axis that identifies and axis in a matric

a.sum(axis=1)
c = np.array([2, 5, 6, 0])
c.sum(axis=0)

#np.sqrt()# will compute sqrt of each value
#np.std()

a = np.array([[2, 3], [2, 3]])

#np can do .dot and / * simple operations natively 
#n = [0: ] included, not included

# be aware when it is refering to each element and each row

d = np.array([[1, 2, 3], [34, 4, 5], [6, 7, 8]])
d[0:2, 2] # prints the 2th element of rows 0 and 1`

# a quick way to build matrix 
e = np.arange(10).reshape(2, 5)
print(e)

#np.vstack() stacks two arrays ontop of eachother 
# takes a tuple, can also stack horizontal hstack()

# np.hsplit and np.vsplit
# np.hsplit(a, 3)
# a > b creates a matrix of true and falses for each value 
# of type bool

#super cool bool math with these bool matrix where we can
# do some set math an transform large parts of the matrix





[[0 1 2 3 4]
 [5 6 7 8 9]]
