In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns; sns.set()


    

In [9]:
array = np.arange(1000)
print(array.size*array.itemsize)

array2 = np.arange(1000)
result = [(x + y) for x, y in zip(array, array2)]


8000


In [12]:
a = np.array(np.random.randn(4, 4, 2))
print(a.ndim)
print(a)

3
[[[ 0.88090636 -0.03861493]
  [ 0.59454374  0.87057752]
  [ 0.3913207   0.17822361]
  [-2.36394285 -0.66311528]]

 [[ 1.26933878  0.24108847]
  [ 0.34337032 -0.16724024]
  [ 0.18806855  0.40522419]
  [-0.38440686 -1.76725822]]

 [[-1.3624359   0.00885936]
  [-0.02806737  0.53971363]
  [-0.57162587 -0.30176184]
  [ 0.66447928  0.52536199]]

 [[ 0.19193372 -0.47994978]
  [-0.65010788  0.88364199]
  [ 0.58964144  0.92388108]
  [-0.48643678  0.7025045 ]]]


In [15]:
b = np.array([[1, 1], [3, 3]], dtype= np.int32)
a.dtype
b.dtype

a.size #total element
a.shape #dimensions

np.zeros((4, 4))
np.linspace(1, 5)

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])